plugins: /verdaccio/plugins
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 30m

middlewares:
  audit:
    enabled: true

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

log:
  - { type: stdout, format: pretty, level: trace }

https:
  enable: true
  key: /verdaccio/ssl/verdaccio-key.pem
  cert: /verdaccio/ssl/verdaccio-cert.pem
  ca: null